# Removing Broadcom
rm ./working/system/vendor/firmware/bcm2079x_firmware.ncd
rm ./working/system/vendor/firmware/bcm2079x_pre_firmware.ncd 
rm ./working/system/vendor/firmware/bcm2079x_firmware.ncd
rm ./working/system/vendor/firmware/bcm2079x_pre_firmware.ncd
# Removing LGE
rm ./working/system/lib/libacdbdata.so
rm ./working/system/lib/libAKM.so
rm ./working/system/lib/libcamera_fast_af.so
rm ./working/system/lib/libmorpho_noise_reduction.so
rm ./working/system/vendor/firmware/keymaster/keymaster.b00
rm ./working/system/vendor/firmware/keymaster/keymaster.b01
rm ./working/system/vendor/firmware/keymaster/keymaster.b02
rm ./working/system/vendor/firmware/keymaster/keymaster.b03
rm ./working/system/vendor/firmware/keymaster/keymaster.mdt
# Removing QCOM
rm ./working/system/bin/ATFWD-daemon
rm ./working/system/bin/bridgemgrd
rm ./working/system/bin/btnvtool
rm ./working/system/bin/diag_klog
rm ./working/system/bin/diag_mdlog
rm ./working/system/bin/ds_fmc_appd
rm ./working/system/bin/efsks
rm ./working/system/bin/hci_qcomm_init
rm ./working/system/bin/ks
rm ./working/system/bin/mm-qcamera-daemon
rm ./working/system/bin/mpdecision
rm ./working/system/bin/netmgrd
rm ./working/system/bin/nl_listener
rm ./working/system/bin/port-bridge
rm ./working/system/bin/qcks
rm ./working/system/bin/qmuxd
rm ./working/system/bin/qseecomd
rm ./working/system/bin/radish
rm ./working/system/bin/rmt_storage
rm ./working/system/bin/sensors.qcom
rm ./working/system/bin/thermald
rm ./working/system/bin/usbhub
rm ./working/system/bin/usbhub_init
rm ./working/system/bin/v4l2-qcamera-app
rm ./working/system/etc/firmware/tzapps.b00
rm ./working/system/etc/firmware/tzapps.b01
rm ./working/system/etc/firmware/tzapps.b02
rm ./working/system/etc/firmware/tzapps.b03
rm ./working/system/etc/firmware/tzapps.mdt
rm ./working/system/etc/firmware/vidc_1080p.fw
rm ./working/system/etc/firmware/vidc.b00
rm ./working/system/etc/firmware/vidc.b01
rm ./working/system/etc/firmware/vidc.b02
rm ./working/system/etc/firmware/vidc.b03
rm ./working/system/etc/firmware/vidc.mdt
rm ./working/system/lib/egl/eglsubAndroid.so
rm ./working/system/lib/egl/libEGL_adreno.so
rm ./working/system/lib/egl/libGLESv1_CM_adreno.so
rm ./working/system/vendor/lib/egl/libGLESv1_CM_adreno.so
rm ./working/system/lib/egl/libGLESv2_adreno.so
rm ./working/system/lib/egl/libplayback_adreno.so
rm ./working/system/lib/egl/libq3dtools_adreno.so
rm ./working/system/lib/libGLES_trace.so
rm ./working/system/lib/libGLESv1_CM.so
rm ./working/system/lib/libGLESv2.so
rm ./working/system/lib/libGLESv3.so
rm ./working/system/vendor/lib/egl/libGLESv1_CM_adreno.so
rm ./working/system/vendor/lib/egl/libGLESv2_adreno.so
rm ./working/system/lib/libq3dtools_adreno.so
rm ./working/system/vendor/lib/egl/libq3dtools_adreno.so
rm ./working/system/lib/hw/flp.msm8960.so
rm ./working/system/lib/hw/gps.msm8960.so
rm ./working/system/lib/hw/sensors.msm8960.so
rm ./working/system/lib/libacdbloader.so
rm ./working/system/lib/libadreno_utils.so
rm ./working/system/vendor/lib/libadreno_utils.so
rm ./working/system/lib/libaudcal.so
rm ./working/system/lib/libaudioalsa.so
rm ./working/system/lib/libC2D2.so
rm ./working/system/vendor/lib/libC2D2.so
rm ./working/system/lib/libc2d30-a3xx.so
rm ./working/system/lib/libc2d30.so
rm ./working/system/vendor/lib/libc2d30-a3xx.so
rm ./working/system/vendor/lib/libc2d30.so
rm ./working/system/lib/libCB.so
rm ./working/system/lib/libchromatix_imx111_default_video.so
rm ./working/system/lib/libchromatix_imx111_preview.so
rm ./working/system/lib/libchromatix_imx111_zsl.so
rm ./working/system/lib/libchromatix_imx119_default_video.so
rm ./working/system/lib/libchromatix_imx119_preview.so
rm ./working/system/lib/libchromatix_mt9e013_default_video.so
rm ./working/system/lib/libchromatix_mt9e013_preview.so
rm ./working/system/lib/libchromatix_mt9e013_video_hfr.so
rm ./working/system/lib/libchromatix_ov5647_default_video.so
rm ./working/system/lib/libchromatix_ov5647_preview.so
rm ./working/system/lib/libchromatix_ov5647_video_hfr.so
rm ./working/system/lib/libchromatix_ov8825_default_video.so
rm ./working/system/lib/libchromatix_ov8825_preview.so
rm ./working/system/lib/libchromatix_ov9726_default_video.so
rm ./working/system/lib/libchromatix_ov9726_preview.so
rm ./working/system/lib/libchromatix_s5k4e1_default_video.so
rm ./working/system/lib/libchromatix_s5k4e1_preview.so
rm ./working/system/lib/libchromatix_vx6953_default_video.so
rm ./working/system/lib/libchromatix_vx6953_preview.so
rm ./working/system/lib/libCommandSvc.so
rm ./working/system/lib/libconfigdb.so
rm ./working/system/lib/libcsd-client.so
rm ./working/system/lib/libdiag.so
rm ./working/system/lib/libdrmdiag.so
rm ./working/system/lib/libdrmfs.so
rm ./working/system/lib/libdrmtime.so
rm ./working/system/lib/libdsi_netctrl.so
rm ./working/system/lib/libdsprofile.so
rm ./working/system/lib/libdss.so
rm ./working/system/lib/libdsucsd.so
rm ./working/system/lib/libdsutils.so
rm ./working/system/lib/libgemini.so
rm ./working/system/lib/libgps.utils.so
rm ./working/system/lib/libgsl.so
rm ./working/system/vendor/lib/libgsl.so
rm ./working/system/lib/libI420colorconvert.so
rm ./working/system/lib/libidl.so
rm ./working/system/lib/libimage-jpeg-dec-omx-comp.so
rm ./working/system/lib/libimage-jpeg-enc-omx-comp.so
rm ./working/system/lib/libimage-omx-common.so
rm ./working/system/lib/libllvm-a3xx.so
rm ./working/system/vendor/lib/libllvm-qcom.so
rm ./working/system/lib/libloc_core.so
rm ./working/system/lib/libloc_eng.so
rm ./working/system/lib/libmercury.so
rm ./working/system/lib/libmmcamera_faceproc.so
rm ./working/system/lib/libmmcamera_frameproc.so
rm ./working/system/lib/libmmcamera_hdr_lib.so
rm ./working/system/lib/libmmcamera_image_stab.so
rm ./working/system/lib/libmmcamera_statsproc31.so
rm ./working/system/lib/libmmcamera_wavelet_lib.so
rm ./working/system/lib/libmm-color-convertor.so
rm ./working/system/lib/libmmipl.so
rm ./working/system/lib/libmmjpeg.so
rm ./working/system/lib/libmmjps.so
rm ./working/system/lib/libmmmpod.so
rm ./working/system/lib/libmmmpo.so
rm ./working/system/lib/libmmstillomx.so
rm ./working/system/lib/libnetmgr.so
rm ./working/system/lib/liboemcamera.so
rm ./working/system/lib/liboemcrypto.so
rm ./working/system/lib/libqcci_legacy.so
rm ./working/system/lib/libqdi.so
rm ./working/system/lib/libqdp.so
rm ./working/system/lib/libqmi_cci.so
rm ./working/system/lib/libqmi_client_qmux.so
rm ./working/system/lib/libqmi_common_so.so
rm ./working/system/lib/libqmi_csi.so
rm ./working/system/lib/libqmi_csvt_srvc.so
rm ./working/system/lib/libqmi_encdec.so
rm ./working/system/lib/libqmiservices.so
rm ./working/system/lib/libqmi.so
rm ./working/system/lib/libQSEEComAPI.so
rm ./working/system/lib/libril-qc-qmi-1.so
rm ./working/system/lib/libril-qcril-hook-oem.so
rm ./working/system/lib/librs_adreno_sha1.so
rm ./working/system/lib/librs_adreno.so
rm ./working/system/vendor/lib/librs_adreno.so
rm ./working/system/vendor/lib/librs_adreno_sha1.so
rm ./working/system/lib/libRSDriver_adreno.so
rm ./working/system/vendor/lib/libRSDriver_adreno.so
rm ./working/system/lib/libsc-a3xx.so
rm ./working/system/vendor/lib/libsc-a3xx.so
rm ./working/system/lib/libsensor1.so
rm ./working/system/lib/libsensor_reg.so
rm ./working/system/lib/libsensor_user_cal.so
rm ./working/system/lib/libstagefright_hdcp.so
rm ./working/system/lib/libxml.so
rm ./working/system/vendor/firmware/a300_pfp.fw
rm ./working/system/vendor/firmware/a300_pm4.fw
rm ./working/system/vendor/firmware/dsps.b00
rm ./working/system/vendor/firmware/dsps.b01
rm ./working/system/vendor/firmware/dsps.b02
rm ./working/system/vendor/firmware/dsps.b03
rm ./working/system/vendor/firmware/dsps.b04
rm ./working/system/vendor/firmware/dsps.b05
rm ./working/system/vendor/firmware/dsps.mdt
rm ./working/system/vendor/firmware/q6.b00
rm ./working/system/vendor/firmware/q6.b01
rm ./working/system/vendor/firmware/q6.b03
rm ./working/system/vendor/firmware/q6.b04
rm ./working/system/vendor/firmware/q6.b05
rm ./working/system/vendor/firmware/q6.b06
rm ./working/system/vendor/firmware/q6.mdt
rm ./working/system/vendor/firmware/wcnss.b00
rm ./working/system/vendor/firmware/wcnss.b01
rm ./working/system/vendor/firmware/wcnss.b02
rm ./working/system/vendor/firmware/wcnss.b04
rm ./working/system/vendor/firmware/wcnss.b05
rm ./working/system/vendor/firmware/wcnss.mdt
rm ./working/system/vendor/lib/libdrmdecrypt.so
rm ./working/system/vendor/lib/libgeofence.so
rm ./working/system/vendor/lib/libizat_core.so
rm ./working/system/vendor/lib/libloc_api_v02.so
rm ./working/system/vendor/lib/libloc_ds_api.so
